<a href="https://colab.research.google.com/github/youjin0512/study_AIs/blob/main/docs/MLs/Regression/01_linearRegression_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Regression (회귀)
 - 데이터
 - 모델
 - 평가

### 1. 데이터 관련

In [20]:
from sklearn import datasets
datasets.load_diabetes(return_X_y=True)   # 대문자 X : x가 여러개, 소문자 y : y는 1개라서
# diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
   

In [7]:
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

In [5]:
type(diabetes_X), type(diabetes_y)

(numpy.ndarray, numpy.ndarray)

In [9]:
diabetes_X.shape, diabetes_y.shape

((442, 10), (442,))

### 2. 모델

In [11]:
from sklearn import linear_model    # linear_model : 선형모델 직선을 가지고 현재 데이터에 대한 직선 찾기

In [12]:
linear_model.LinearRegression()   # .LinearRegression() : 자체는 class

LinearRegression()

In [13]:
linearRegression = linear_model.LinearRegression()   # 학습 장소 선택   # linearRegression : class 생성자

In [14]:
linearRegression.fit(diabetes_X, diabetes_y)  # 학습 진행

LinearRegression()

### 3. 평가

In [17]:
linearRegression.predict(diabetes_X[:2])

array([206.11667725,  68.07103297])

In [18]:
diabetes_X[:2]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405]])

In [19]:
diabetes_X[:2], diabetes_y[:2]

(array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
         -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
         -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405]]),
 array([151.,  75.]))

In [21]:
linearRegression.predict(diabetes_X[:2])

array([206.11667725,  68.07103297])